version: '3'

services:
  dash:
    build: ./flaskapp
    volumes:
      - ./flaskapp:/code
    ports:
      - "5000:80"
    depends_on:
      - redis

  feeder:
    build: ./pyfeeder
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  flaskapp:
