version: '3'

services:
  dash:
    build: ./flaskapp
    volumes:
      - ./flaskapp:/code
    ports:
      - "5000:80"
    depends_on:
      - redis
    restart: always

  feeder:
    build: ./pyfeeder
    volumes:
      - ./resolv.conf:/etc/redis.conf
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always


# docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" --build-arg GEMS_KEYS="$(cat ~/GEMS_KEYS.yaml)"
# docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" --build-arg GEMS_KEYS="$(cat ~/gems_api.yml)"